version: 2

sources:
# Sources listed below should closely resemble the names of your Fivetran connectors. Names are at your descretion. Schema's will mirror your destination schemas.

  - name: logs # this can be whatever I want
    schema: fivetran_log # this is the name of a connector with a SINGLE SCHEMA
    tables:
      - name: account
      - name: connector
      - name: log
      
